version: '3.8'

services:

  web:
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - media_data:/app/media
      - sqlite_data:/app/data
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_data:/app/media
    depends_on:
      - web
    restart: always

volumes:
  media_data:
  sqlite_data:
