# Generated by Django 3.1.12 on 2026-03-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20260303_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_time',
        ),
    ]
