# Generated by Django 3.1.12 on 2026-03-12 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_auto_20260310_1231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0005_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('test_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sample_collection', models.CharField(choices=[('Lab Visit', 'Lab Visit'), ('Home Collection', 'Home Collection')], default='Lab Visit', max_length=20)),
                ('payment_type', models.CharField(default='Online', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('booking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
