# Generated by Django 3.1.12 on 2026-03-16 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0012_auto_20260316_2117'),
        ('appointments', '0006_labappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labappointment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Doctor.lab'),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
