# Generated by Django 3.1.12 on 2026-03-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20260316_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='test_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
