# Generated by Django 6.0.4 on 2026-05-06 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0022_alter_doctor_id_alter_doctoravailability_id_and_more'),
        ('appointments', '0010_payment_razorpay_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date', 'status'], name='appointment_doctor__f0e3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='appointment_patient_94a7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='appointment_created_5f1d98_idx'),
        ),
        migrations.AddIndex(
            model_name='labappointment',
            index=models.Index(fields=['lab', 'appointment_date', 'status'], name='appointment_lab_id_231dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='labappointment',
            index=models.Index(fields=['patient'], name='appointment_patient_6e7185_idx'),
        ),
        migrations.AddIndex(
            model_name='labappointment',
            index=models.Index(fields=['created_at'], name='appointment_created_4ce153_idx'),
        ),
    ]
