# Generated by Django 3.1.12 on 2026-02-28 06:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField()),
                ('existing_diseases', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('consultation_mode', models.CharField(choices=[('Online', 'Online'), ('In-person', 'In-person')], max_length=20)),
                ('payment_type', models.CharField(default='Online', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('clinic_name', models.CharField(blank=True, max_length=150, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('available_days', models.JSONField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('appointment_duration', models.IntegerField(blank=True, default=15, null=True)),
                ('consultation_type', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Both', 'Both')], default='Offline', max_length=20, null=True)),
                ('online_consultation_time', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_of_appointment', models.CharField(blank=True, choices=[('In-person', 'In-person'), ('Online', 'Online')], default='In-person', max_length=50, null=True)),
                ('education_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_number', models.CharField(blank=True, max_length=15, null=True)),
                ('degree_certificate', models.ImageField(blank=True, null=True, upload_to='doctor_degrees/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='hospital_photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='hospital_photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='hospital_photos/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='hospital_photos/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='hospital_photos/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='hospital_photos/')),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to='hospital_photos/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(db_index=True, max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter valid contact number (10-15 digits).', regex='^\\d{10,15}$')])),
                ('emergency_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter valid contact number (10-15 digits).', regex='^\\d{10,15}$')])),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter valid 6-digit pincode.', regex='^\\d{6}$')])),
                ('lab_type', models.CharField(choices=[('Pathology', 'Pathology'), ('Radiology', 'Radiology'), ('Diagnostic Center', 'Diagnostic Center'), ('Multi-specialty', 'Multi-specialty')], db_index=True, default='Pathology', max_length=50)),
                ('home_sample_collection', models.BooleanField(default=False)),
                ('operating_days', models.CharField(max_length=100)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('average_report_time', models.CharField(max_length=50)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnostic Lab',
                'verbose_name_plural': 'Diagnostic Labs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Doctor.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('test_image', models.ImageField(blank=True, null=True, upload_to='test_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medical Test',
                'verbose_name_plural': 'Medical Tests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('test_image', models.ImageField(blank=True, null=True, upload_to='lab_test_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='Doctor.lab')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_in_labs', to='Doctor.test')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['test__name'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='lab_reports/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Doctor.labappointment')),
            ],
        ),
        migrations.AddField(
            model_name='labappointment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.test'),
        ),
    ]
