# Generated by Django 3.1.12 on 2026-02-28 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['lab'], name='Doctor_labt_lab_id_51fab4_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['test'], name='Doctor_labt_test_id_164f34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labtest',
            unique_together={('lab', 'test')},
        ),
        migrations.AddIndex(
            model_name='lab',
            index=models.Index(fields=['city'], name='Doctor_lab_city_5b78f1_idx'),
        ),
        migrations.AddIndex(
            model_name='lab',
            index=models.Index(fields=['lab_type'], name='Doctor_lab_lab_typ_ea1d93_idx'),
        ),
        migrations.AddIndex(
            model_name='lab',
            index=models.Index(fields=['is_verified'], name='Doctor_lab_is_veri_ae36db_idx'),
        ),
    ]
