# Generated by Django 3.1.12 on 2026-03-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20260228_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
