# Generated by Django 3.1.12 on 2026-03-07 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_delete_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='reason',
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
    ]
