# Generated by Django 3.1.12 on 2026-03-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20260307_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
