# Generated by Django 3.1.12 on 2026-03-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_auto_20260307_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='day',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='start_time',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
    ]
