# Generated by Django 3.1.12 on 2026-03-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_labavailability'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='labtest',
            name='Doctor_labt_lab_id_51fab4_idx',
        ),
        migrations.RemoveIndex(
            model_name='labtest',
            name='Doctor_labt_test_id_164f34_idx',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test_image',
        ),
        migrations.RemoveField(
            model_name='test',
            name='default_price',
        ),
        migrations.AlterField(
            model_name='labtest',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='Doctor.lab'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.test'),
        ),
    ]
