# Generated by Django 3.1.12 on 2026-03-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0009_auto_20260314_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labavailability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
