# Generated by Django 3.1.12 on 2026-03-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_auto_20260314_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='Doctor.test'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['lab'], name='Doctor_labt_lab_id_51fab4_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['test'], name='Doctor_labt_test_id_164f34_idx'),
        ),
    ]
