# Generated by Django 3.1.12 on 2026-03-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_labappointment'),
        ('Doctor', '0011_auto_20260314_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='appointments.labappointment'),
        ),
        migrations.DeleteModel(
            name='LabAppointment',
        ),
    ]
