# Generated by Django 3.1.12 on 2026-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_auto_20260316_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['test__name']},
        ),
        migrations.RemoveIndex(
            model_name='labtest',
            name='Doctor_labt_lab_id_51fab4_idx',
        ),
        migrations.RemoveIndex(
            model_name='labtest',
            name='Doctor_labt_test_id_164f34_idx',
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
