# Generated by Django 3.1.12 on 2026-03-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0013_auto_20260318_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
