# Generated by Django 3.1.12 on 2026-03-18 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0014_auto_20260318_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='Doctor.test'),
        ),
    ]
