# Generated by Django 3.1.12 on 2026-03-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0018_medicalrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['id']},
        ),
    ]
