# Generated by Django 3.1.12 on 2026-03-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0019_auto_20260322_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='user',
            new_name='patient',
        ),
    ]
